import * as path from 'path';
import type { OpenAPIV3 } from 'openapi-types';
import type { ProjectConfig } from '../types/index.js';
import { toPascalCase, toCamelCase, toKebabCase } from '../utils/naming.js';
import { formatCode } from '../utils/codeFormatting.js';
import { logger } from '../utils/logger.js';
import { writeFile } from '../utils/fileSystem.js';

/**
 * Options that control which kinds of tests are emitted.
 */
export interface PlaywrightTestOptions {
  /** Emit Playwright API-request tests (default: true) */
  generateApiTests?: boolean;
  /** Emit Playwright browser E2E tests (default: true) */
  generateE2eTests?: boolean;
  /** Base URL used in API tests, e.g. "http://localhost:3000" */
  baseUrl?: string;
  /** Whether to include authentication setup (default: true) */
  includeAuth?: boolean;
}

export class PlaywrightTestGenerator {
  constructor(private projectConfig: ProjectConfig) {}

  // ──────────────────────────────────────────────────────────────
  // Public API
  // ──────────────────────────────────────────────────────────────

  /**
   * Generate test files for every resource group found in `spec`.
   * Returns the list of written file paths.
   */
  async generate(
    spec: OpenAPIV3.Document,
    endpoints: string[],
    options: PlaywrightTestOptions = {}
  ): Promise<string[]> {
    logger.info('Generating Playwright tests...');
    const generatedFiles: string[] = [];

    const {
      generateApiTests = true,
      generateE2eTests = true,
      baseUrl = 'http://localhost:3000',
      includeAuth = true,
    } = options;

    const resourceGroups = this.groupEndpointsByResource(spec, endpoints);

    for (const [resourceName, operations] of Object.entries(resourceGroups)) {
      if (generateApiTests) {
        const apiFile = await this.generateApiTestFile(
          resourceName,
          operations,
          spec,
          baseUrl,
          includeAuth
        );
        generatedFiles.push(apiFile);
      }

      if (generateE2eTests) {
        const e2eFile = await this.generateE2eTestFile(resourceName, operations, spec);
        generatedFiles.push(e2eFile);
      }
    }

    // Write a shared fixtures / helpers file once
    const fixturesFile = await this.generateFixturesFile(baseUrl, includeAuth);
    generatedFiles.push(fixturesFile);

    logger.info(`Generated ${generatedFiles.length} Playwright test files`);
    return generatedFiles;
  }

  // ──────────────────────────────────────────────────────────────
  // Resource grouping (same helper pattern as other generators)
  // ──────────────────────────────────────────────────────────────

  private groupEndpointsByResource(
    spec: OpenAPIV3.Document,
    endpoints: string[]
  ): Record<string, any[]> {
    const groups: Record<string, any[]> = {};

    Object.entries(spec.paths).forEach(([pathStr, pathItem]) => {
      if (endpoints.length > 0 && !endpoints.includes(pathStr)) return;

      Object.entries(pathItem as any).forEach(([method, operation]: [string, any]) => {
        if (!['get', 'post', 'put', 'patch', 'delete'].includes(method)) return;

        const resourceName = operation.tags?.[0] || this.extractResourceFromPath(pathStr);

        if (!groups[resourceName]) {
          groups[resourceName] = [];
        }

        groups[resourceName].push({ method, path: pathStr, operation });
      });
    });

    return groups;
  }

  private extractResourceFromPath(pathStr: string): string {
    const parts = pathStr.split('/').filter(Boolean);
    const resourcePart = parts.find(
      p => !p.startsWith('{') && p !== 'api' && !p.startsWith('v')
    );
    return resourcePart || 'api';
  }

  // ──────────────────────────────────────────────────────────────
  // API test file  (uses Playwright's APIRequestContext)
  // ──────────────────────────────────────────────────────────────

  private async generateApiTestFile(
    resourceName: string,
    operations: any[],
    spec: OpenAPIV3.Document,
    baseUrl: string,
    includeAuth: boolean
  ): Promise<string> {
    const featureName = toCamelCase(resourceName);
    const resourcePascal = toPascalCase(resourceName);

    const testCases = operations.map(op =>
      this.buildApiTestCase(op.method, op.path, op.operation, resourceName, spec)
    );

    const authSetup = includeAuth
      ? `\n  // Set auth token from environment or login fixture
  request.defaults.headers['Authorization'] = \`Bearer \${process.env.API_TOKEN ?? ''}\`;`
      : '';

    const code = `/**
 * Playwright API tests for ${resourceName}
 * Generated by Swagger MCP
 *
 * Run with:  npx playwright test ${toKebabCase(resourceName)}.api.spec.ts
 */

import { test, expect } from '@playwright/test';

const BASE_URL = process.env.API_BASE_URL ?? '${baseUrl}';

test.describe('${resourcePascal} API', () => {${authSetup}

${testCases.join('\n\n')}
});
`;

    const formattedCode = await formatCode(code);
    const outputPath = path.join(
      this.projectConfig.paths.tests,
      'api',
      `${toKebabCase(resourceName)}.api.spec.ts`
    );

    await writeFile(outputPath, formattedCode);
    logger.info(`Generated API test: ${outputPath}`);
    return outputPath;
  }

  private buildApiTestCase(
    method: string,
    pathStr: string,
    operation: any,
    resourceName: string,
    spec: OpenAPIV3.Document
  ): string {
    const operationId =
      operation.operationId || this.generateOperationName(method, pathStr);
    const description =
      operation.summary ||
      operation.description ||
      `${method.toUpperCase()} ${pathStr}`;

    const pathParams = this.extractPathParams(pathStr);
    const successStatus = this.getSuccessStatus(method, operation);
    const responseType = this.getResponseType(operation);

    // Build URL expression
    const urlExpr =
      pathParams.length > 0
        ? '`${BASE_URL}' +
          pathStr.replace(/{([^}]+)}/g, (_m, p) => `\${sample${toPascalCase(p)}Id}`) +
          '`'
        : `\`\${BASE_URL}${pathStr}\``;

    // Variable declarations for path params
    const paramDecls = pathParams
      .map(p => `  const sample${toPascalCase(p)}Id = 1; // TODO: replace with a real fixture ID`)
      .join('\n');

    // Request body
    const requestBody = operation.requestBody?.content?.['application/json']?.schema;
    const sampleBody = requestBody
      ? this.generateSampleBody(requestBody, spec)
      : null;

    const bodySection = sampleBody
      ? `\n  const requestBody = ${JSON.stringify(sampleBody, null, 4).replace(/^/gm, '  ').trim()};\n`
      : '';

    const fetchOptions = this.buildFetchOptions(method, sampleBody);

    const responseCheck =
      responseType === 'array'
        ? `  expect(Array.isArray(body)).toBe(true);`
        : responseType === 'object'
          ? `  expect(body).toMatchObject({});`
          : '';

    return `  test('${description}', async ({ request }) => {
${paramDecls ? paramDecls + '\n' : ''}${bodySection}
    const response = await request.${method}(${urlExpr}${fetchOptions});

    expect(response.status()).toBe(${successStatus});
${successStatus !== 204 ? `    const body = await response.json();\n${responseCheck}` : ''}
  });`;
  }

  private buildFetchOptions(method: string, sampleBody: Record<string, any> | null): string {
    if (['post', 'put', 'patch'].includes(method) && sampleBody) {
      return `, { data: requestBody }`;
    }
    return '';
  }

  // ──────────────────────────────────────────────────────────────
  // E2E test file  (browser-level UI interactions)
  // ──────────────────────────────────────────────────────────────

  private async generateE2eTestFile(
    resourceName: string,
    operations: any[],
    spec: OpenAPIV3.Document
  ): Promise<string> {
    const featureName = toCamelCase(resourceName);
    const resourcePascal = toPascalCase(resourceName);
    const resourceKebab = toKebabCase(resourceName);

    const hasCreate = operations.some(op => op.method === 'post');
    const hasRead = operations.some(op => op.method === 'get');
    const hasUpdate = operations.some(
      op => ['put', 'patch'].includes(op.method) && op.path.includes('{')
    );
    const hasDelete = operations.some(op => op.method === 'delete' && op.path.includes('{'));

    // Gather fields from the first POST operation (if any)
    const createOp = operations.find(op => op.method === 'post');
    const formFields = createOp
      ? this.extractFormFields(
          createOp.operation.requestBody?.content?.['application/json']?.schema,
          spec
        )
      : [];

    const testCases: string[] = [];

    if (hasRead) {
      testCases.push(this.buildE2eListTest(resourcePascal, resourceKebab));
    }

    if (hasCreate && formFields.length > 0) {
      testCases.push(this.buildE2eCreateTest(resourcePascal, resourceKebab, formFields));
    }

    if (hasUpdate && formFields.length > 0) {
      testCases.push(this.buildE2eUpdateTest(resourcePascal, resourceKebab, formFields));
    }

    if (hasDelete) {
      testCases.push(this.buildE2eDeleteTest(resourcePascal, resourceKebab));
    }

    const code = `/**
 * Playwright E2E tests for ${resourceName}
 * Generated by Swagger MCP
 *
 * Run with:  npx playwright test ${resourceKebab}.e2e.spec.ts
 */

import { test, expect } from '@playwright/test';
import { loginFixture } from '../fixtures/auth.fixture';

test.describe('${resourcePascal} — E2E', () => {
  test.beforeEach(async ({ page }) => {
    await loginFixture(page);
    await page.goto('/dashboard/${resourceKebab}');
    await page.waitForLoadState('networkidle');
  });

${testCases.join('\n\n')}
});
`;

    const formattedCode = await formatCode(code);
    const outputPath = path.join(
      this.projectConfig.paths.tests,
      'e2e',
      `${resourceKebab}.e2e.spec.ts`
    );

    await writeFile(outputPath, formattedCode);
    logger.info(`Generated E2E test: ${outputPath}`);
    return outputPath;
  }

  private buildE2eListTest(resourcePascal: string, resourceKebab: string): string {
    return `  test('should display the ${resourcePascal} list page', async ({ page }) => {
    await expect(page).toHaveURL(/.*${resourceKebab}.*/);
    // The page heading or a recognisable element should be visible
    await expect(page.getByRole('heading', { name: /${resourcePascal}/i }).first()).toBeVisible();
  });`;
  }

  private buildE2eCreateTest(
    resourcePascal: string,
    resourceKebab: string,
    fields: Array<{ name: string; type: string; sampleValue: string }>
  ): string {
    const fillSteps = fields
      .map(f => {
        if (f.type === 'textarea') {
          return `    await page.getByLabel(/${f.name}/i).fill('${f.sampleValue}');`;
        }
        return `    await page.getByLabel(/${f.name}/i).fill('${f.sampleValue}');`;
      })
      .join('\n');

    return `  test('should create a new ${resourcePascal}', async ({ page }) => {
    // Open the create dialog / form
    await page.getByRole('button', { name: /create/i }).click();

    // Fill in the form fields
${fillSteps}

    // Submit
    await page.getByRole('button', { name: /submit|save|create/i }).last().click();

    // Verify success toast / updated list
    await expect(page.getByText(/created successfully/i)).toBeVisible({ timeout: 5000 });
  });`;
  }

  private buildE2eUpdateTest(
    resourcePascal: string,
    resourceKebab: string,
    fields: Array<{ name: string; type: string; sampleValue: string }>
  ): string {
    const firstField = fields[0];
    const updateValue = `Updated ${firstField?.sampleValue ?? 'value'}`;

    return `  test('should update an existing ${resourcePascal}', async ({ page }) => {
    // Click on the first item to open detail / edit view
    await page.getByRole('link').first().click();
    await page.waitForLoadState('networkidle');

    // Open edit form
    await page.getByRole('button', { name: /edit/i }).click();

    // Update the first editable field
    const firstField = page.getByLabel(/${firstField?.name ?? 'name'}/i);
    await firstField.clear();
    await firstField.fill('${updateValue}');

    // Submit
    await page.getByRole('button', { name: /save|update/i }).last().click();

    // Verify success
    await expect(page.getByText(/updated successfully/i)).toBeVisible({ timeout: 5000 });
  });`;
  }

  private buildE2eDeleteTest(resourcePascal: string, resourceKebab: string): string {
    return `  test('should delete a ${resourcePascal}', async ({ page }) => {
    // Click on the first item
    await page.getByRole('link').first().click();
    await page.waitForLoadState('networkidle');

    // Click the delete button and confirm
    await page.getByRole('button', { name: /delete/i }).click();
    await page.getByRole('button', { name: /confirm|yes/i }).click();

    // Should navigate back to the list and show success
    await expect(page).toHaveURL(/.*${resourceKebab}.*/);
    await expect(page.getByText(/deleted successfully/i)).toBeVisible({ timeout: 5000 });
  });`;
  }

  // ──────────────────────────────────────────────────────────────
  // Shared fixtures file
  // ──────────────────────────────────────────────────────────────

  private async generateFixturesFile(baseUrl: string, includeAuth: boolean): Promise<string> {
    const authHelper = includeAuth
      ? `/**
 * Log in via the UI and persist the authentication state.
 * Adjust selectors to match your application's login page.
 */
export async function loginFixture(page: Page): Promise<void> {
  const email = process.env.TEST_USER_EMAIL ?? 'test@example.com';
  const password = process.env.TEST_USER_PASSWORD ?? 'password';

  // Skip login if already authenticated (cookie / localStorage present)
  const token = await page.evaluate(() => localStorage.getItem('token'));
  if (token) return;

  await page.goto('/login');
  await page.getByLabel(/email/i).fill(email);
  await page.getByLabel(/password/i).fill(password);
  await page.getByRole('button', { name: /sign in|log in/i }).click();
  await page.waitForURL(/dashboard/, { timeout: 10_000 });
}

/**
 * Obtain a raw API token for use in APIRequestContext tests.
 */
export async function getApiToken(request: APIRequestContext): Promise<string> {
  const response = await request.post(\`\${BASE_URL}/auth/login\`, {
    data: {
      email: process.env.TEST_USER_EMAIL ?? 'test@example.com',
      password: process.env.TEST_USER_PASSWORD ?? 'password',
    },
  });

  const body = await response.json();
  return body?.data?.token ?? body?.token ?? '';
}`
      : `/**
 * Placeholder – auth is disabled.
 * Fill in as needed.
 */
export async function loginFixture(_page: Page): Promise<void> {}
export async function getApiToken(_request: APIRequestContext): Promise<string> { return ''; }`;

    const code = `/**
 * Shared Playwright test fixtures & helpers
 * Generated by Swagger MCP
 */

import type { Page, APIRequestContext } from '@playwright/test';

export const BASE_URL = process.env.API_BASE_URL ?? '${baseUrl}';

${authHelper}
`;

    const formattedCode = await formatCode(code);
    const outputPath = path.join(this.projectConfig.paths.tests, 'fixtures', 'auth.fixture.ts');

    await writeFile(outputPath, formattedCode);
    logger.info(`Generated fixtures file: ${outputPath}`);
    return outputPath;
  }

  // ──────────────────────────────────────────────────────────────
  // Helpers
  // ──────────────────────────────────────────────────────────────

  private extractPathParams(pathStr: string): string[] {
    const matches = pathStr.match(/{([^}]+)}/g);
    if (!matches) return [];
    return matches.map(m => m.slice(1, -1));
  }

  private generateOperationName(method: string, pathStr: string): string {
    const pathParts = pathStr.split('/').filter(p => p && !p.startsWith('{'));
    const resource = pathParts[pathParts.length - 1] || pathParts[pathParts.length - 2] || 'resource';

    const operationMap: Record<string, string> = {
      get: pathStr.includes('{')
        ? `get${toPascalCase(resource)}Detail`
        : `get${toPascalCase(resource)}`,
      post: `create${toPascalCase(resource)}`,
      put: `update${toPascalCase(resource)}`,
      patch: `update${toPascalCase(resource)}`,
      delete: `delete${toPascalCase(resource)}`,
    };

    return operationMap[method] || `${method}${toPascalCase(resource)}`;
  }

  private getSuccessStatus(method: string, operation: any): number {
    if (operation.responses?.['200']) return 200;
    if (operation.responses?.['201']) return 201;
    if (operation.responses?.['204']) return 204;
    // Fall back to sensible defaults
    if (method === 'post') return 201;
    if (method === 'delete') return 204;
    return 200;
  }

  /** Returns 'array' | 'object' | 'void' based on the success response schema */
  private getResponseType(operation: any): 'array' | 'object' | 'void' {
    const response =
      operation.responses?.['200'] ||
      operation.responses?.['201'] ||
      operation.responses?.['204'];

    if (!response?.content?.['application/json']?.schema) return 'void';

    const schema = response.content['application/json'].schema;
    if (schema.type === 'array' || schema.items) return 'array';
    return 'object';
  }

  /**
   * Build a minimal sample request body from the schema, suitable for tests.
   */
  private generateSampleBody(
    schema: any,
    spec: OpenAPIV3.Document
  ): Record<string, any> | null {
    const resolved = this.resolveSchema(schema, spec);
    if (!resolved?.properties) return null;

    const body: Record<string, any> = {};
    const required: string[] = resolved.required ?? [];

    for (const [fieldName, fieldSchema] of Object.entries<any>(resolved.properties)) {
      // Only include required fields in the sample to keep payloads minimal
      if (!required.includes(fieldName)) continue;
      body[fieldName] = this.sampleValue(fieldName, fieldSchema);
    }

    // If no required fields, include all fields
    if (Object.keys(body).length === 0) {
      for (const [fieldName, fieldSchema] of Object.entries<any>(resolved.properties)) {
        body[fieldName] = this.sampleValue(fieldName, fieldSchema);
      }
    }

    return body;
  }

  private sampleValue(fieldName: string, schema: any): any {
    if (schema.example !== undefined) return schema.example;
    if (schema.default !== undefined) return schema.default;

    if (schema.enum?.length) return schema.enum[0];

    const lower = fieldName.toLowerCase();

    switch (schema.type) {
      case 'string':
        if (schema.format === 'email' || lower.includes('email')) return 'test@example.com';
        if (schema.format === 'date' || lower.includes('date')) return '2024-01-01';
        if (schema.format === 'date-time') return '2024-01-01T00:00:00Z';
        if (schema.format === 'uuid') return '00000000-0000-0000-0000-000000000001';
        if (lower.includes('url') || lower.includes('link')) return 'https://example.com';
        if (lower.includes('name')) return 'Test Name';
        if (lower.includes('title')) return 'Test Title';
        if (lower.includes('description') || lower.includes('body')) return 'Test description';
        if (lower.includes('phone')) return '+1234567890';
        return 'test-value';
      case 'integer':
      case 'number':
        if (schema.minimum !== undefined) return schema.minimum;
        return 1;
      case 'boolean':
        return true;
      case 'array':
        return [];
      default:
        return null;
    }
  }

  private resolveSchema(schema: any, spec: OpenAPIV3.Document): any {
    if (!schema?.$ref) return schema;
    const refPath = schema.$ref.replace('#/', '').split('/');
    let resolved: any = spec;
    for (const part of refPath) {
      resolved = resolved?.[part];
    }
    return resolved ?? schema;
  }

  private extractFormFields(
    schema: any,
    spec: OpenAPIV3.Document
  ): Array<{ name: string; type: string; sampleValue: string }> {
    const resolved = this.resolveSchema(schema, spec);
    if (!resolved?.properties) return [];

    return Object.entries<any>(resolved.properties).map(([name, prop]) => ({
      name,
      type:
        prop.type === 'string' && prop.maxLength && prop.maxLength > 100 ? 'textarea' : 'input',
      sampleValue: String(this.sampleValue(name, prop)),
    }));
  }

  async updateEndpoint(endpointPath: string, method: string, spec: any): Promise<string | null> {
    logger.info(`Updating Playwright tests for endpoint: ${method.toUpperCase()} ${endpointPath}`);
    return null;
  }
}
