import * as fs from 'fs/promises';
import * as path from 'path';
import type { OpenAPIV3 } from 'openapi-types';
import type { ProjectConfig } from '../types/index.js';
import { toPascalCase, toCamelCase } from '../utils/naming.js';
import { formatCode } from '../utils/codeFormatting.js';
import { logger } from '../utils/logger.js';
import { writeFile } from '../utils/fileSystem.js';

export class ServiceGenerator {
  constructor(private projectConfig: ProjectConfig) {}

  async generate(spec: OpenAPIV3.Document, endpoints: string[]): Promise<string[]> {
    logger.info('Generating API services...');
    const generatedFiles: string[] = [];

    // Group endpoints by resource
    const resourceGroups = this.groupEndpointsByResource(spec, endpoints);

    for (const [resourceName, operations] of Object.entries(resourceGroups)) {
      const filePath = await this.generateServiceFile(resourceName, operations, spec);
      generatedFiles.push(filePath);
    }

    logger.info(`Generated ${generatedFiles.length} service files`);
    return generatedFiles;
  }

  private groupEndpointsByResource(
    spec: OpenAPIV3.Document,
    endpoints: string[]
  ): Record<string, any[]> {
    const groups: Record<string, any[]> = {};

    Object.entries(spec.paths).forEach(([pathStr, pathItem]) => {
      if (endpoints.length > 0 && !endpoints.includes(pathStr)) return;

      Object.entries(pathItem as any).forEach(([method, operation]: [string, any]) => {
        if (!['get', 'post', 'put', 'patch', 'delete'].includes(method)) return;

        const resourceName = operation.tags?.[0] || this.extractResourceFromPath(pathStr);

        if (!groups[resourceName]) {
          groups[resourceName] = [];
        }

        groups[resourceName].push({
          method,
          path: pathStr,
          operation,
        });
      });
    });

    return groups;
  }

  private extractResourceFromPath(pathStr: string): string {
    const parts = pathStr.split('/').filter(Boolean);
    const resourcePart = parts.find(p => !p.startsWith('{') && p !== 'api' && !p.startsWith('v'));
    return resourcePart || 'api';
  }

  private async generateServiceFile(
    resourceName: string,
    operations: any[],
    spec: OpenAPIV3.Document
  ): Promise<string> {
    const featureName = toCamelCase(resourceName);
    const serviceFunctions: string[] = [];

    // Generate service function for each operation
    for (const { method, path: pathStr, operation } of operations) {
      const func = this.generateServiceFunction(method, pathStr, operation, resourceName);
      serviceFunctions.push(func);
    }

    const code = `/**
 * API services for ${resourceName}
 * Generated by Swagger MCP
 */

import axiosInstance from '@/api/axiosInstance';
import type {
  ${this.generateTypeImports(operations, featureName)}
} from '@/types/api/${featureName}';

${serviceFunctions.join('\n\n')}
`;

    const formattedCode = await formatCode(code);
    const outputPath = path.join(this.projectConfig.paths.api, `${featureName}Service.ts`);

    await writeFile(outputPath, formattedCode);

    logger.info(`Generated service: ${outputPath}`);
    return outputPath;
  }

  private generateServiceFunction(
    method: string,
    pathStr: string,
    operation: any,
    resourceName: string
  ): string {
    const operationId = operation.operationId || this.generateOperationName(method, pathStr);
    const functionName = `${toCamelCase(operationId)}Service`;
    const description = operation.summary || operation.description || `${method.toUpperCase()} ${pathStr}`;

    // Extract path parameters
    const pathParams = this.extractPathParams(pathStr);
    
    // Extract query parameters
    const queryParams = operation.parameters?.filter((p: any) => p.in === 'query') || [];
    
    // Check for request body
    const hasRequestBody = !!operation.requestBody;

    // Determine response type
    const response = operation.responses?.['200'] || operation.responses?.['201'] || operation.responses?.['204'];
    const responseType = this.getResponseType(response, operationId);

    // Build function signature
    let params: string[] = [];
    
    // Add path parameters
    if (pathParams.length > 0) {
      params.push(...pathParams.map(p => `${p}: string | number`));
    }

    // Add request body
    if (hasRequestBody) {
      params.push(`data: ${toPascalCase(operationId)}Request`);
    }

    // Add query parameters as object
    if (queryParams.length > 0) {
      params.push(`params?: ${toPascalCase(operationId)}Params`);
    }

    const paramsStr = params.join(', ');

    // Build URL path with template literals
    const urlPath = this.buildUrlPath(pathStr, pathParams);

    // Build axios call
    let axiosCall: string;
    const axiosMethod = method.toLowerCase();

    if (hasRequestBody && (axiosMethod === 'post' || axiosMethod === 'put' || axiosMethod === 'patch')) {
      if (queryParams.length > 0) {
        axiosCall = `axiosInstance.${axiosMethod}<${responseType}>(\n    ${urlPath},\n    data,\n    { params }\n  )`;
      } else {
        axiosCall = `axiosInstance.${axiosMethod}<${responseType}>(\n    ${urlPath},\n    data\n  )`;
      }
    } else if (axiosMethod === 'delete') {
      if (queryParams.length > 0) {
        axiosCall = `axiosInstance.delete<void>(\n    ${urlPath},\n    { params }\n  )`;
      } else {
        axiosCall = `axiosInstance.delete<void>(\n    ${urlPath}\n  )`;
      }
    } else {
      // GET request
      if (queryParams.length > 0) {
        axiosCall = `axiosInstance.get<${responseType}>(\n    ${urlPath},\n    { params }\n  )`;
      } else {
        axiosCall = `axiosInstance.get<${responseType}>(\n    ${urlPath}\n  )`;
      }
    }

    // Handle void return for DELETE
    const returnStatement = axiosMethod === 'delete' && !response?.content 
      ? 'return;'
      : 'return response.data;';

    return `/**
 * ${description}
 */
export const ${functionName} = async (${paramsStr}): Promise<${responseType}> => {
  const response = await ${axiosCall};
  ${returnStatement}
};`;
  }

  private extractPathParams(pathStr: string): string[] {
    const matches = pathStr.match(/{([^}]+)}/g);
    if (!matches) return [];
    return matches.map(m => m.slice(1, -1));
  }

  private buildUrlPath(pathStr: string, pathParams: string[]): string {
    if (pathParams.length === 0) {
      return `'${pathStr}'`;
    }

    let url = pathStr;
    pathParams.forEach(param => {
      url = url.replace(`{${param}}`, `\${${param}}`);
    });

    return `\`${url}\``;
  }

  private getResponseType(response: any, operationId: string): string {
    if (!response) return 'void';
    
    const content = response.content?.['application/json'];
    if (!content) return 'void';

    const schema = content.schema;
    if (schema?.$ref) {
      const typeName = schema.$ref.split('/').pop();
      return toPascalCase(typeName);
    }

    // Default response type based on operation
    return `${toPascalCase(operationId)}Response`;
  }

  private generateOperationName(method: string, pathStr: string): string {
    const pathParts = pathStr.split('/').filter(p => p && !p.startsWith('{'));
    const resource = pathParts[pathParts.length - 1] || pathParts[pathParts.length - 2];

    const operationMap: Record<string, string> = {
      get: pathStr.includes('{') ? `get${toPascalCase(resource)}Detail` : `get${toPascalCase(resource)}`,
      post: `create${toPascalCase(resource)}`,
      put: `update${toPascalCase(resource)}`,
      patch: `update${toPascalCase(resource)}`,
      delete: `delete${toPascalCase(resource)}`,
    };

    return operationMap[method] || `${method}${toPascalCase(resource)}`;
  }

  private generateTypeImports(operations: any[], featureName: string): string {
    const types = new Set<string>();

    operations.forEach(({ method, operation }) => {
      const operationId = operation.operationId || '';
      
      // Request types
      if (operation.requestBody) {
        types.add(`${toPascalCase(operationId)}Request`);
      }

      // Response types
      const response = operation.responses?.['200'] || operation.responses?.['201'];
      if (response) {
        types.add(`${toPascalCase(operationId)}Response`);
      }

      // Params types
      const queryParams = operation.parameters?.filter((p: any) => p.in === 'query');
      if (queryParams && queryParams.length > 0) {
        types.add(`${toPascalCase(operationId)}Params`);
      }
    });

    return Array.from(types).join(',\n  ');
  }

  async updateEndpoint(path: string, method: string, spec: any): Promise<string | null> {
    logger.info(`Updating service for endpoint: ${method.toUpperCase()} ${path}`);
    return null;
  }
}
