import * as fs from 'fs/promises';
import * as path from 'path';
import type { OpenAPIV3 } from 'openapi-types';
import type { ProjectConfig } from '../types/index.js';
import { toPascalCase, toCamelCase } from '../utils/naming.js';
import { formatCode } from '../utils/codeFormatting.js';
import { logger } from '../utils/logger.js';
import { writeFile } from '../utils/fileSystem.js';

export class TypeGenerator {
  private projectConfig: ProjectConfig;

  constructor(projectConfig: ProjectConfig) {
    this.projectConfig = projectConfig;
  }

  async generate(spec: OpenAPIV3.Document, endpoints: string[]): Promise<string[]> {
    const generatedFiles: string[] = [];
    const schemas = spec.components?.schemas || {};

    // Group schemas by tag/resource
    const resourceGroups = this.groupSchemasByResource(spec, endpoints);

    for (const [resourceName, schemaNames] of Object.entries(resourceGroups)) {
      const filePath = await this.generateTypeFile(resourceName, schemaNames, schemas, spec);
      generatedFiles.push(filePath);
    }

    return generatedFiles;
  }

  private groupSchemasByResource(
    spec: OpenAPIV3.Document,
    endpoints: string[]
  ): Record<string, Set<string>> {
    const groups: Record<string, Set<string>> = {};

    Object.entries(spec.paths).forEach(([pathStr, pathItem]) => {
      if (endpoints.length > 0 && !endpoints.includes(pathStr)) return;

      Object.entries(pathItem as any).forEach(([method, operation]: [string, any]) => {
        if (!['get', 'post', 'put', 'patch', 'delete'].includes(method)) return;

        const resourceName = operation.tags?.[0] || this.extractResourceFromPath(pathStr);

        if (!groups[resourceName]) {
          groups[resourceName] = new Set();
        }

        // Extract schema names from operations
        const requestBody = operation.requestBody?.content?.['application/json']?.schema;
        if (requestBody?.$ref) {
          groups[resourceName].add(this.extractSchemaName(requestBody.$ref));
        }

        Object.values(operation.responses || {}).forEach((response: any) => {
          const responseSchema = response?.content?.['application/json']?.schema;
          if (responseSchema?.$ref) {
            groups[resourceName].add(this.extractSchemaName(responseSchema.$ref));
          }
        });
      });
    });

    return groups;
  }

  private extractResourceFromPath(pathStr: string): string {
    const parts = pathStr.split('/').filter(Boolean);
    const resourcePart = parts.find(p => !p.startsWith('{') && p !== 'api' && !p.startsWith('v'));
    return resourcePart || 'api';
  }

  private extractSchemaName(ref: string): string {
    const parts = ref.split('/');
    return parts[parts.length - 1];
  }

  private async generateTypeFile(
    resourceName: string,
    schemaNames: Set<string>,
    schemas: Record<string, any>,
    spec: OpenAPIV3.Document
  ): Promise<string> {
    const featureName = toCamelCase(resourceName);
    const interfaces: string[] = [];

    // Generate interfaces from schemas
    for (const schemaName of schemaNames) {
      const schema = schemas[schemaName];
      if (schema) {
        interfaces.push(this.generateInterface(schemaName, schema));
      }
    }

    // Generate common response types
    const commonTypes = `
/**
 * Standard API response wrapper
 */
export interface ApiResponse<T = any> {
  status: number;
  message: string;
  data: T;
}

/**
 * Pagination metadata
 */
export interface PaginationMeta {
  current_page: number;
  per_page: number;
  total: number;
  total_pages: number;
  next: string | null;
  previous: string | null;
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
  status: number;
  message: string;
  data: T[];
  pagination: PaginationMeta;
}
`;

    const code = `/**
 * Type definitions for ${resourceName} API
 * Generated by Swagger MCP
 */

${interfaces.join('\n\n')}

${commonTypes}
`;

    const formattedCode = await formatCode(code);
    const outputPath = path.join(this.projectConfig.paths.types, `${featureName}.ts`);

    await writeFile(outputPath, formattedCode);

    logger.info(`Generated types: ${outputPath}`);
    return outputPath;
  }

  private generateInterface(name: string, schema: any): string {
    const pascalName = toPascalCase(name);
    const properties = Object.entries(schema.properties || {})
      .map(([propName, propSchema]: [string, any]) => {
        const optional = !schema.required?.includes(propName);
        const type = this.getTypeScriptType(propSchema);
        const description = propSchema.description ? `  /** ${propSchema.description} */\n` : '';
        return `${description}  ${propName}${optional ? '?' : ''}: ${type};`;
      })
      .join('\n');

    return `/**
 * ${schema.description || pascalName}
 */
export interface ${pascalName} {
${properties}
}`;
  }

  private getTypeScriptType(schema: any): string {
    if (!schema) return 'any';

    if (schema.$ref) {
      return toPascalCase(this.extractSchemaName(schema.$ref));
    }

    if (schema.type === 'array') {
      return `${this.getTypeScriptType(schema.items)}[]`;
    }

    if (schema.type === 'object') {
      if (schema.additionalProperties) {
        return `Record<string, ${this.getTypeScriptType(schema.additionalProperties)}>`;
      }
      return 'Record<string, any>';
    }

    switch (schema.type) {
      case 'string':
        return 'string';
      case 'number':
      case 'integer':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'null':
        return 'null';
      default:
        return 'any';
    }
  }

  async updateEndpoint(
    endpointPath: string,
    method: string,
    updatedSpec: any
  ): Promise<string | null> {
    logger.info(`Updating types for endpoint: ${method.toUpperCase()} ${endpointPath}`);
    return null;
  }
}
