import * as fs from 'fs/promises';
import * as path from 'path';
import type { OpenAPIV3 } from 'openapi-types';
import type { ProjectConfig } from '../types/index.js';
import { toPascalCase, toCamelCase } from '../utils/naming.js';
import { formatCode } from '../utils/codeFormatting.js';
import { logger } from '../utils/logger.js';
import { writeFile } from '../utils/fileSystem.js';

export class ValidationGenerator {
  constructor(private projectConfig: ProjectConfig) {}

  async generate(spec: OpenAPIV3.Document, endpoints: string[]): Promise<string[]> {
    logger.info('Generating Zod validation schemas...');
    const generatedFiles: string[] = [];

    // Group endpoints by resource (only POST/PUT/PATCH need validation)
    const resourceGroups = this.groupEndpointsByResource(spec, endpoints);

    for (const [resourceName, operations] of Object.entries(resourceGroups)) {
      const filePath = await this.generateValidationFile(resourceName, operations, spec);
      if (filePath) {
        generatedFiles.push(filePath);
      }
    }

    logger.info(`Generated ${generatedFiles.length} validation files`);
    return generatedFiles;
  }

  private groupEndpointsByResource(
    spec: OpenAPIV3.Document,
    endpoints: string[]
  ): Record<string, any[]> {
    const groups: Record<string, any[]> = {};

    Object.entries(spec.paths).forEach(([pathStr, pathItem]) => {
      if (endpoints.length > 0 && !endpoints.includes(pathStr)) return;

      Object.entries(pathItem as any).forEach(([method, operation]: [string, any]) => {
        // Only process mutations that have request bodies
        if (!['post', 'put', 'patch'].includes(method)) return;
        if (!operation.requestBody) return;

        const resourceName = operation.tags?.[0] || this.extractResourceFromPath(pathStr);

        if (!groups[resourceName]) {
          groups[resourceName] = [];
        }

        groups[resourceName].push({
          method,
          path: pathStr,
          operation,
        });
      });
    });

    return groups;
  }

  private extractResourceFromPath(pathStr: string): string {
    const parts = pathStr.split('/').filter(Boolean);
    const resourcePart = parts.find(p => !p.startsWith('{') && p !== 'api' && !p.startsWith('v'));
    return resourcePart || 'api';
  }

  private async generateValidationFile(
    resourceName: string,
    operations: any[],
    spec: OpenAPIV3.Document
  ): Promise<string | null> {
    if (operations.length === 0) return null;

    const featureName = toCamelCase(resourceName);
    const schemas: string[] = [];

    // Generate validation schema for each operation
    for (const { method, path: pathStr, operation } of operations) {
      const schema = this.generateValidationSchema(method, pathStr, operation, spec);
      if (schema) {
        schemas.push(schema);
      }
    }

    if (schemas.length === 0) return null;

    const code = `/**
 * Zod validation schemas for ${resourceName}
 * Generated by Swagger MCP
 */

import { z } from 'zod';

${schemas.join('\n\n')}
`;

    const formattedCode = await formatCode(code);
    const outputPath = path.join(this.projectConfig.paths.validations, `${featureName}.ts`);

    await writeFile(outputPath, formattedCode);

    logger.info(`Generated validations: ${outputPath}`);
    return outputPath;
  }

  private generateValidationSchema(
    method: string,
    pathStr: string,
    operation: any,
    spec: OpenAPIV3.Document
  ): string | null {
    const requestBody = operation.requestBody?.content?.['application/json']?.schema;
    if (!requestBody) return null;

    const operationId = operation.operationId || this.generateOperationName(method, pathStr);
    const schemaName = `${toCamelCase(operationId)}Schema`;
    const typeName = `${toPascalCase(operationId)}FormData`;

    // Resolve schema if it's a $ref
    const schema = this.resolveSchema(requestBody, spec);
    if (!schema || !schema.properties) return null;

    const fields = this.generateSchemaFields(schema);

    return `/**
 * Validation schema for ${operationId}
 */
export const ${schemaName} = z.object({
${fields}
});

/**
 * Type inference from ${schemaName}
 */
export type ${typeName} = z.infer<typeof ${schemaName}>;`;
  }

  private resolveSchema(schema: any, spec: OpenAPIV3.Document): any {
    if (schema.$ref) {
      const refPath = schema.$ref.replace('#/', '').split('/');
      let resolved: any = spec;
      for (const part of refPath) {
        resolved = resolved[part];
      }
      return resolved;
    }
    return schema;
  }

  private generateSchemaFields(schema: any): string {
    const properties = schema.properties || {};
    const required = schema.required || [];
    const fields: string[] = [];

    for (const [fieldName, fieldSchema] of Object.entries(properties)) {
      const field = fieldSchema as any;
      const isRequired = required.includes(fieldName);
      const validation = this.getZodValidation(fieldName, field, isRequired);
      
      fields.push(`  ${fieldName}: ${validation},`);
    }

    return fields.join('\n');
  }

  private getZodValidation(fieldName: string, schema: any, isRequired: boolean): string {
    let validation = this.getBaseZodType(schema);
    const rules: string[] = [];

    // String validations
    if (schema.type === 'string') {
      if (schema.minLength) {
        rules.push(`.min(${schema.minLength}, '${this.getFieldLabel(fieldName)} must be at least ${schema.minLength} characters')`);
      }
      if (schema.maxLength) {
        rules.push(`.max(${schema.maxLength}, '${this.getFieldLabel(fieldName)} must not exceed ${schema.maxLength} characters')`);
      }
      if (schema.pattern) {
        rules.push(`.regex(/${schema.pattern}/, '${this.getFieldLabel(fieldName)} format is invalid')`);
      }
      if (schema.format === 'email') {
        validation = "z.string().email('Invalid email address')";
        rules.length = 0; // Clear other rules for email
      }
      if (schema.format === 'url' || schema.format === 'uri') {
        validation = "z.string().url('Invalid URL')";
        rules.length = 0;
      }
      if (schema.format === 'uuid') {
        validation = "z.string().uuid('Invalid UUID')";
        rules.length = 0;
      }
    }

    // Number validations
    if (schema.type === 'number' || schema.type === 'integer') {
      if (schema.minimum !== undefined) {
        rules.push(`.min(${schema.minimum}, '${this.getFieldLabel(fieldName)} must be at least ${schema.minimum}')`);
      }
      if (schema.maximum !== undefined) {
        rules.push(`.max(${schema.maximum}, '${this.getFieldLabel(fieldName)} must not exceed ${schema.maximum}')`);
      }
      if (schema.type === 'integer') {
        rules.push(`.int('${this.getFieldLabel(fieldName)} must be an integer')`);
      }
      if (schema.minimum !== undefined && schema.minimum > 0) {
        rules.push(`.positive('${this.getFieldLabel(fieldName)} must be positive')`);
      }
    }

    // Array validations
    if (schema.type === 'array') {
      if (schema.minItems) {
        rules.push(`.min(${schema.minItems}, 'At least ${schema.minItems} item(s) required')`);
      }
      if (schema.maxItems) {
        rules.push(`.max(${schema.maxItems}, 'Maximum ${schema.maxItems} item(s) allowed')`);
      }
    }

    // Required validation
    if (isRequired && schema.type === 'string') {
      rules.unshift(`.min(1, '${this.getFieldLabel(fieldName)} is required')`);
    }

    // Combine validation rules
    if (rules.length > 0) {
      validation += rules.join('');
    }

    // Make optional if not required
    if (!isRequired) {
      validation += '.optional()';
    }

    return validation;
  }

  private getBaseZodType(schema: any): string {
    if (schema.$ref) {
      return 'z.any()'; // For $ref, let TypeScript handle the typing
    }

    if (schema.enum) {
      const values = schema.enum.map((v: string) => `'${v}'`).join(', ');
      return `z.enum([${values}])`;
    }

    if (schema.type === 'array') {
      const itemType = this.getBaseZodType(schema.items || { type: 'any' });
      return `z.array(${itemType})`;
    }

    if (schema.type === 'object') {
      if (schema.additionalProperties) {
        const valueType = this.getBaseZodType(schema.additionalProperties);
        return `z.record(z.string(), ${valueType})`;
      }
      return 'z.object({})';
    }

    switch (schema.type) {
      case 'string':
        return 'z.string()';
      case 'number':
        return 'z.number()';
      case 'integer':
        return 'z.number()';
      case 'boolean':
        return 'z.boolean()';
      case 'null':
        return 'z.null()';
      default:
        return 'z.any()';
    }
  }

  private getFieldLabel(fieldName: string): string {
    return fieldName
      .replace(/([A-Z])/g, ' $1')
      .replace(/_/g, ' ')
      .replace(/^./, str => str.toUpperCase())
      .trim();
  }

  private generateOperationName(method: string, pathStr: string): string {
    const pathParts = pathStr.split('/').filter(p => p && !p.startsWith('{'));
    const resource = pathParts[pathParts.length - 1] || pathParts[pathParts.length - 2];

    const operationMap: Record<string, string> = {
      post: `create${toPascalCase(resource)}`,
      put: `update${toPascalCase(resource)}`,
      patch: `update${toPascalCase(resource)}`,
    };

    return operationMap[method] || `${method}${toPascalCase(resource)}`;
  }

  async updateEndpoint(path: string, method: string, spec: any): Promise<string | null> {
    logger.info(`Updating validation for endpoint: ${method.toUpperCase()} ${path}`);
    return null;
  }
}
